site_name: Geo Activity Playground
site_url: 'https://martin-ueding.github.io/geo-activity-playground/'

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      media: "(prefers-color-scheme: light)"
    - scheme: slate
      primary: amber
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      media: "(prefers-color-scheme: dark)"

nav:
  - index.md
  - Installation:
    - install-on-linux.md
    - install-on-windows.md
    - add-local-bin-to-path.md
  - create-a-base-directory.md
  - starting-the-webserver.md
  - record-activities.md
  - Activity Sources:
    - import-activity-files.md
    - connect-strava-api.md
    - moving-from-strava.md
    - advanced-metadata-extraction.md
  - get-help.md
  - Features:
    - features/upload.md
    - features/kind-rename.md
  - How-To Guides:
    - plan-missing-tile-rides.md
    - create-a-privacy-zone.md
    - set-up-a-development-environment.md
  - Explanation:
    - explorer-tiles.md
    - eddington-number.md
  - changelog.md
  - acknowledgments.md
  - Deployment with Docker:
    - using-git-version-via-docker.md
    - using-git-version-via-docker-compose.md
    - using-git-version-via-docker-compose-and-tailscale-vpn.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
